# Generated by Django 5.0 on 2025-02-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="security_question",
            field=models.CharField(
                default="What is your favorite movie", max_length=255
            ),
        ),
    ]
